/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisualIngrediente;

import Controllers.IngredienteController;
import Entidades.Ingrediente;
import VisualProducto.ListaProducto;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MartinC
 */
public class ListaIngredientes extends javax.swing.JFrame {

    boolean contadorClick;
    IngredienteController ic = new IngredienteController();
    ArrayList<Ingrediente> listaIngredientes;
    DefaultListModel ingredientes = new DefaultListModel();
    ListaProducto listaProducto;

    public ListaIngredientes(ListaProducto listaProducto) {
        initComponents();
        this.listaProducto = listaProducto;
        ingredientesJList.setModel(ingredientes);
        actualizarDatos();
        this.setLocationRelativeTo(null);
        setearPantalla();
    }

    public ListaIngredientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaCompleta = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pantalla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientesJList = new javax.swing.JList<>();
        buscarTxt = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        cerrarBtn = new javax.swing.JLabel();
        eliminarBtn = new javax.swing.JButton();
        agregarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pantallaCompleta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(204, 204, 204));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 36)); // NOI18N
        jLabel1.setText("Ingredientes");
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        pantallaCompleta.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 70));

        pantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingredientesJList.setFont(new java.awt.Font("Arial Narrow", 0, 26)); // NOI18N
        ingredientesJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingredientesJListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ingredientesJList);

        pantalla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 310, 240));

        buscarTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buscarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarTxtKeyPressed(evt);
            }
        });
        pantalla.add(buscarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 50));

        buscarBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });
        pantalla.add(buscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 110, 50));

        cerrarBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cerrarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarBtn.setText("X");
        cerrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarBtnMouseClicked(evt);
            }
        });
        pantalla.add(cerrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 60, 70));

        eliminarBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        eliminarBtn.setForeground(new java.awt.Color(255, 0, 0));
        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });
        pantalla.add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 120, 50));

        agregarBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        agregarBtn.setText("Nuevo");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });
        pantalla.add(agregarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 120, 50));

        pantallaCompleta.add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 460, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaCompleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        VerIngrediente ver = new VerIngrediente(this);
        ver.setVisible(true);
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void ingredientesJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingredientesJListMouseClicked
        contadorClick = false;
        if (evt.getClickCount() == 2) {
            int index = ingredientesJList.getSelectedIndex();
            int id = listaIngredientes.get(index).getId();
            VerIngrediente ver = new VerIngrediente(id, this);
            ver.setVisible(true);
        }
    }//GEN-LAST:event_ingredientesJListMouseClicked

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        buscar();
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void cerrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarBtnMouseClicked
        buscarTxt.setText("");
        actualizarDatos();
    }//GEN-LAST:event_cerrarBtnMouseClicked

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Seguro quiere eliminar?", "Eliminar",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int index = ingredientesJList.getSelectedIndex();
            int id = listaIngredientes.get(index).getId();
            ic.eliminarIngrediente(id);
            actualizarDatos();
        }
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        listaProducto.actualizarDatos();
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void buscarTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTxtKeyPressed
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            buscar();
        }
    }//GEN-LAST:event_buscarTxtKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaIngredientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaIngredientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JTextField buscarTxt;
    private javax.swing.JLabel cerrarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JList<String> ingredientesJList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel pantalla;
    private javax.swing.JPanel pantallaCompleta;
    // End of variables declaration//GEN-END:variables

    private void llenarPantalla() {
        ingredientes.removeAllElements();
        String[] lista = ic.llenarPantalla(listaIngredientes);
        for (String listas : lista) {
            ingredientes.addElement(listas);
        }
    }

    public void actualizarDatos() {
        listaIngredientes = ic.devolverListaIngredientes();
        listaProducto.actualizarDatos();
        llenarPantalla();
    }

    private void buscar() {
        listaIngredientes = ic.devolverListaIngredientes();
        String buscar = buscarTxt.getText();
        listaIngredientes = ic.buscar(buscar, listaIngredientes);
        llenarPantalla();
    }
    
    private void setearPantalla() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int margenDerecho = 50;
        int x = screenSize.width - getWidth() - margenDerecho;  // Posición con margen a la derecha
        int y = screenSize.height / 2 - getHeight() / 2;
        this.setLocation(x, y);
    }
}
