/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisualIngrediente;

import Controllers.IngredienteController;
import Entidades.Ingrediente;

/**
 *
 * @author MartinC
 */
public class VerIngrediente extends javax.swing.JFrame {

    IngredienteController ic = new IngredienteController();
    int idIngrediente;
    ListaIngredientes lista;

    public VerIngrediente(ListaIngredientes lista) {
        initComponents();
        idIngrediente = -10;
        this.lista = lista;
        this.setLocationRelativeTo(lista);
    }

    public VerIngrediente(int idIngrediente, ListaIngredientes lista) {
        initComponents();
        this.idIngrediente = idIngrediente;
        llenarPantalla();
        this.lista = lista;
        this.setLocationRelativeTo(lista);
    }

    public VerIngrediente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaCompleta = new javax.swing.JPanel();
        menuPl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pantallaPl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textPrecio = new javax.swing.JTextField();
        precioPorUnidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        guardarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pantallaCompleta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPl.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel1.setText("Ingrediente");

        javax.swing.GroupLayout menuPlLayout = new javax.swing.GroupLayout(menuPl);
        menuPl.setLayout(menuPlLayout);
        menuPlLayout.setHorizontalGroup(
            menuPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        menuPlLayout.setVerticalGroup(
            menuPlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pantallaCompleta.add(menuPl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 70));

        pantallaPl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel4.setText("Nombre:");
        pantallaPl.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        textNombre.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        pantallaPl.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 260, -1));

        textPrecio.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        pantallaPl.add(textPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, -1));

        precioPorUnidad.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        precioPorUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilo", "1/2 kilo", "100 gramos", "Litro", "Cc", "Unidad" }));
        pantallaPl.add(precioPorUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 150, -1));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel5.setText("Precio:");
        pantallaPl.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel6.setText("x");
        pantallaPl.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, 30));

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel7.setText("-");
        pantallaPl.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 40, -1));

        jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jLabel8.setText("-");
        pantallaPl.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 40, 30));

        guardarBtn.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });
        pantallaPl.add(guardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        pantallaCompleta.add(pantallaPl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 350, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        String nombre = textNombre.getText();
        double precio = Double.valueOf(textPrecio.getText());
        String aux = "";
        switch (precioPorUnidad.getSelectedIndex()) {
            case 0:
                aux = "k";
                precio = precio / 1000;
                break;
            case 1:
                aux = "k";
                precio = precio / 500;
                break;
            case 2:
                aux = "g";
                precio = precio / 100;
                break;
            case 3:
                aux = "l";
                precio = precio / 1000;
                break;
            case 4:
                aux = "c";
                break;
            case 5:
                aux = "u";
                break;
        }
        Ingrediente ingrediente = new Ingrediente();
        ingrediente.setId(idIngrediente);
        ingrediente.setNombre(nombre);
        ingrediente.setPrecioUnidad(precio);
        ingrediente.setUnidad(aux);
        if (idIngrediente == -10) {
            ic.crearIngrediente(ingrediente);
        } else {
            ic.actualizarIngrediente(ingrediente);
        }
        lista.actualizarDatos();
        this.dispose();
    }//GEN-LAST:event_guardarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerIngrediente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerIngrediente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel menuPl;
    private javax.swing.JPanel pantallaCompleta;
    private javax.swing.JPanel pantallaPl;
    private javax.swing.JComboBox<String> precioPorUnidad;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables

    private void llenarPantalla() {
        Ingrediente ingrediente = ic.getElementById(idIngrediente);
        textNombre.setText(ingrediente.getNombre());
        double precio = ingrediente.getPrecioUnidad();
        String aux = ingrediente.getUnidad();
        switch (aux) {
            case "k":
                precioPorUnidad.setSelectedIndex(0);
                precio = precio * 1000;
                break;
            case "g":
                precioPorUnidad.setSelectedIndex(2);
                precio = precio * 100;
                break;
            case "l":
                precioPorUnidad.setSelectedIndex(3);
                precio = precio * 1000;
                break;
            case "c":
                precioPorUnidad.setSelectedIndex(4);
                break;
            case "u":
                precioPorUnidad.setSelectedIndex(5);
                break;
        }
        textPrecio.setText(String.valueOf(precio));
    }
}
