/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisualProducto;

import Controllers.ProductoController;
import Entidades.Producto;
import VisualIngrediente.ListaIngredientes;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MartinC
 */
public class ListaProducto extends javax.swing.JFrame {

    ProductoController pc = new ProductoController();
    DefaultListModel recetas = new DefaultListModel();
    ArrayList<Producto> listaProductos;
    boolean contadorClick;

    public ListaProducto() {
        initComponents();
        actualizarDatos();
        productosJList.setModel(recetas);
        this.setLocationRelativeTo(null);
        setearPantalla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantallaCompleta = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pantalla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productosJList = new javax.swing.JList<>();
        todosIngredienteBtn = new javax.swing.JButton();
        agregarRecetaBtn = new javax.swing.JButton();
        buscarTxt = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        cerrarBtn = new javax.swing.JLabel();
        eliminarBtn = new javax.swing.JButton();
        x25 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantallaCompleta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(204, 204, 204));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 40)); // NOI18N
        jLabel1.setText("Recetas");
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 70));

        pantallaCompleta.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 70));

        pantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productosJList.setFont(new java.awt.Font("Arial Narrow", 0, 30)); // NOI18N
        productosJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosJListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productosJList);

        pantalla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 470, 380));

        todosIngredienteBtn.setBackground(new java.awt.Color(255, 255, 255));
        todosIngredienteBtn.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        todosIngredienteBtn.setText("Ver Ingredientes");
        todosIngredienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosIngredienteBtnActionPerformed(evt);
            }
        });
        pantalla.add(todosIngredienteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, 40));

        agregarRecetaBtn.setBackground(new java.awt.Color(255, 255, 255));
        agregarRecetaBtn.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        agregarRecetaBtn.setText("Agregar Receta");
        agregarRecetaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarRecetaBtnActionPerformed(evt);
            }
        });
        pantalla.add(agregarRecetaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, 40));

        buscarTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buscarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarTxtKeyPressed(evt);
            }
        });
        pantalla.add(buscarTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 50));

        buscarBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });
        pantalla.add(buscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 110, 50));

        cerrarBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cerrarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarBtn.setText("X");
        cerrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarBtnMouseClicked(evt);
            }
        });
        pantalla.add(cerrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 70, 70));

        eliminarBtn.setBackground(new java.awt.Color(255, 255, 255));
        eliminarBtn.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        eliminarBtn.setText("Eliminar");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });
        pantalla.add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 170, 40));

        x25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        x25.setText("x 2,5");
        x25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x25ActionPerformed(evt);
            }
        });
        pantalla.add(x25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 170, 40));

        pantallaCompleta.add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 700, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantallaCompleta, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productosJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosJListMouseClicked
        contadorClick = false;
        if (evt.getClickCount() == 2) {
            int index = productosJList.getSelectedIndex();
            int id = listaProductos.get(index).getId();
            VerProducto ver = new VerProducto(id, this);
            ver.setVisible(true);
        }
    }//GEN-LAST:event_productosJListMouseClicked

    private void todosIngredienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosIngredienteBtnActionPerformed
        ListaIngredientes listaIngre = new ListaIngredientes(this);
        listaIngre.setVisible(true);
    }//GEN-LAST:event_todosIngredienteBtnActionPerformed

    private void agregarRecetaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarRecetaBtnActionPerformed
        VerProducto ver = new VerProducto(this);
        ver.setVisible(true);
    }//GEN-LAST:event_agregarRecetaBtnActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        buscar();
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void cerrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarBtnMouseClicked
        buscarTxt.setText("");
        actualizarDatos();
    }//GEN-LAST:event_cerrarBtnMouseClicked

    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Seguro quiere eliminar?", "Eliminar",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            int index = productosJList.getSelectedIndex();
            int id = listaProductos.get(index).getId();
            eliminarProducto(id);
        }
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void buscarTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTxtKeyPressed
        char tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_ENTER) {
            buscar();
        }
    }//GEN-LAST:event_buscarTxtKeyPressed

    private void x25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x25ActionPerformed
        llenarPantalla();
    }//GEN-LAST:event_x25ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarRecetaBtn;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JTextField buscarTxt;
    private javax.swing.JLabel cerrarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel pantalla;
    private javax.swing.JPanel pantallaCompleta;
    private javax.swing.JList<String> productosJList;
    private javax.swing.JButton todosIngredienteBtn;
    private javax.swing.JToggleButton x25;
    // End of variables declaration//GEN-END:variables

    private void llenarPantalla() {
        recetas.removeAllElements();
        boolean multiplicador;
        multiplicador = x25.isSelected();
        String[] lista = pc.llenarPantalla(listaProductos, multiplicador);
        for (String listas : lista) {
            recetas.addElement(listas);
        }
    }

    public void actualizarDatos() {
        listaProductos = pc.devolverProductos();
        llenarPantalla();
    }

    public void eliminarProducto(int id) {
        if (pc.eliminarProducto(id)) {
            actualizarDatos();
        }
    }

    public void buscar() {
        listaProductos = pc.devolverProductos();
        String buscar = buscarTxt.getText();
        listaProductos = pc.buscar(buscar, listaProductos);
        llenarPantalla();
    }

    private void setearPantalla() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = 50;  // Posición izquierda
        int y = screenSize.height / 2 - getHeight() / 2;
        this.setLocation(x, y);
    }
}
